name: Pytest

on:
  pull_request:
  push:

defaults:
  run:
    shell: /bin/bash --noprofile --norc -Eeuxo pipefail {0}

jobs:
  run_tests:
    runs-on: ${{ matrix.os-version }}
    continue-on-error: ${{ matrix.pre-release }}
    strategy:
      fail-fast: false
      matrix:
        os-version: ['ubuntu-latest']
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        pre-release: [false]
        include:
          - os-version: 'ubuntu-latest'
            python-version: '3.x'
            pre-release: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: ${{ matrix.pre-release }}
        check-latest: ${{ matrix.pre-release }}

    - name: Install pytest and dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install .[test]

    # https://github.com/ymyzk/tox-gh-actions then?
    - name: Test with pytest
      run: |
        python3 -m pytest -vv
